flyway:
  locations: db/migration/{vendor}
spring:
  datasource:
    url: jdbc:h2:mem:hero-ability;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
---
spring:
  profiles: default
logging:
  level:
    com.github: TRACE
    org.hibernate: DEBUG
---
spring:
  profiles: dev
logging:
  level:
    com.github: TRACE
    org.hibernate: DEBUG
---
spring:
  profiles: prod
logging:
  level:
    com.github: INFO
    org.hibernate: WARN
